# Generated by Django 4.2.5 on 2023-09-08 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='name',
            field=models.CharField(default='Interview Object', max_length=100, unique=True),
        ),
    ]
