# Generated by Django 4.2.5 on 2023-09-08 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0002_interview_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='problem',
            field=models.TextField(blank=True, null=True),
        ),
    ]
