version: "3.9"
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: kuber
    ports:
      - "5432:5432"

  permify:
    image: permify/permify
    volumes:
      - ./config/:/config
    command: ["serve", "-c=/config/permify_config.yaml"]
    depends_on:
      - postgres
    ports:
      - "3476:3476"
