version: '3.9'
services:

  # db:
  #   image: postgres
  #   environment:
  #     POSTGRES_USER: root
  #     POSTGRES_PASSWORD: root
  #     POSTGRES_DB: kuber
  #   ports:
  #     - "1486:5432"

  envoy:
    image: envoyproxy/envoy:v1.25.3
    command: ["envoy", "-c", "/etc/envoy.yaml", "--service-cluster", "envoy"]
    volumes:
      - ./envoy.yaml:/etc/envoy.yaml
    ports:
      - "8080:8080"
      - "9901:9901"
