version: "3.9"
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: kuber
    ports:
      - "5432:5432"

  permify:
    image: permify/permify
    volumes:
      - ./config/:/config
    command: ["serve", "-c=/config/permify_config.yaml"]
    depends_on:
      - postgres
    ports:
      - "3476:3476"

  vault:
    image: vault:latest
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=myroot
      - VAULT_DEV_LISTEN_ADDRESS=0.0.0.0:8200
    ports:
      - "8200:8200"
