version: "3.9"
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: kuber
    network_mode: host

  redis:
    image: redis:latest
    network_mode: host

  vault:
    image: vault:1.13.3
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=myroot
      - VAULT_DEV_LISTEN_ADDRESS=0.0.0.0:8200
    network_mode: host

  rest_api:
    build:
      context: .
      dockerfile: dockerfiles/rest.dockerfile
    environment:
      - DEBUG=True
    depends_on:
      - postgres
      - redis
    volumes:
      - ./rest:/rest
    network_mode: host

  ui:
    build:
      context: .
      dockerfile: dockerfiles/ui.dockerfile
    depends_on:
      - rest_api
      - postgres
      - redis
    environment:
      - NODE_ENV=development
    volumes:
      - ./ui:/usr/src/app
    network_mode: host

  userinterface:
    build:
      context: .
      dockerfile: dockerfiles/userinterface.dockerfile
    environment:
      - NODE_ENV=development
      - PORT=4000
    volumes:
      - ./userinterface:/usr/src/app
    network_mode: host
