# Generated by Django 4.2 on 2023-06-07 11:25

import uuid

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Containers",
            fields=[
                (
                    "ID",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "file",
                    models.CharField(
                        choices=[("docker", "docker"), ("compose", "docker-compose")],
                        max_length=10,
                    ),
                ),
                ("config", models.JSONField()),
                (
                    "container_ids",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=100), size=None
                    ),
                ),
            ],
        ),
    ]
