# Generated by Django 4.2 on 2023-04-14 06:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("container", "0001_initial"),
        ("environment", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="usercontainers",
            name="user_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="container",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="container",
            name="environment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="environment.dockerenvironment",
            ),
        ),
        migrations.AddConstraint(
            model_name="usercontainers",
            constraint=models.UniqueConstraint(
                fields=("user_id", "container_id"), name="user_container_pk"
            ),
        ),
    ]
