# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from definitions import execute_pb2 as execute__pb2


class ExecuteStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.execute_command = channel.stream_stream(
                '/execution.Execute/execute_command',
                request_serializer=execute__pb2.ExecuteRequest.SerializeToString,
                response_deserializer=execute__pb2.ExecutionResponse.FromString,
                )


class ExecuteServicer(object):
    """Missing associated documentation comment in .proto file."""

    def execute_command(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ExecuteServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'execute_command': grpc.stream_stream_rpc_method_handler(
                    servicer.execute_command,
                    request_deserializer=execute__pb2.ExecuteRequest.FromString,
                    response_serializer=execute__pb2.ExecutionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'execution.Execute', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Execute(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def execute_command(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/execution.Execute/execute_command',
            execute__pb2.ExecuteRequest.SerializeToString,
            execute__pb2.ExecutionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
