# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: execute.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rexecute.proto\x12\texecution\"F\n\x0e\x45xecuteRequest\x12\x16\n\x0e\x63ontainer_name\x18\x01 \x01(\t\x12\x0f\n\x07\x63ommand\x18\x02 \x01(\t\x12\x0b\n\x03\x64ir\x18\x03 \x01(\t\"$\n\x11\x45xecutionResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2Y\n\x07\x45xecute\x12N\n\x0f\x65xecute_command\x12\x19.execution.ExecuteRequest\x1a\x1c.execution.ExecutionResponse\"\x00\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'execute_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_EXECUTEREQUEST']._serialized_start=28
  _globals['_EXECUTEREQUEST']._serialized_end=98
  _globals['_EXECUTIONRESPONSE']._serialized_start=100
  _globals['_EXECUTIONRESPONSE']._serialized_end=136
  _globals['_EXECUTE']._serialized_start=138
  _globals['_EXECUTE']._serialized_end=227
# @@protoc_insertion_point(module_scope)
