# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from definitions import files_pb2 as files__pb2


class FilesStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.copyFileToContainer = channel.unary_unary(
                '/files.Files/copyFileToContainer',
                request_serializer=files__pb2.File.SerializeToString,
                response_deserializer=files__pb2.CopyResponse.FromString,
                )
        self.getFile = channel.unary_stream(
                '/files.Files/getFile',
                request_serializer=files__pb2.FileDetails.SerializeToString,
                response_deserializer=files__pb2.FilesResponse.FromString,
                )
        self.getDirectory = channel.unary_unary(
                '/files.Files/getDirectory',
                request_serializer=files__pb2.FolderDetails.SerializeToString,
                response_deserializer=files__pb2.DirectoryStrcuture.FromString,
                )


class FilesServicer(object):
    """Missing associated documentation comment in .proto file."""

    def copyFileToContainer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getDirectory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FilesServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'copyFileToContainer': grpc.unary_unary_rpc_method_handler(
                    servicer.copyFileToContainer,
                    request_deserializer=files__pb2.File.FromString,
                    response_serializer=files__pb2.CopyResponse.SerializeToString,
            ),
            'getFile': grpc.unary_stream_rpc_method_handler(
                    servicer.getFile,
                    request_deserializer=files__pb2.FileDetails.FromString,
                    response_serializer=files__pb2.FilesResponse.SerializeToString,
            ),
            'getDirectory': grpc.unary_unary_rpc_method_handler(
                    servicer.getDirectory,
                    request_deserializer=files__pb2.FolderDetails.FromString,
                    response_serializer=files__pb2.DirectoryStrcuture.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'files.Files', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Files(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def copyFileToContainer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/files.Files/copyFileToContainer',
            files__pb2.File.SerializeToString,
            files__pb2.CopyResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def getFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/files.Files/getFile',
            files__pb2.FileDetails.SerializeToString,
            files__pb2.FilesResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def getDirectory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/files.Files/getDirectory',
            files__pb2.FolderDetails.SerializeToString,
            files__pb2.DirectoryStrcuture.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
