# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: files.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x66iles.proto\x12\x05\x66iles\"U\n\x04\x46ile\x12\x11\n\tfile_name\x18\x01 \x01(\t\x12\x0c\n\x04path\x18\x02 \x01(\t\x12\x16\n\x0e\x63ontainer_name\x18\x03 \x01(\t\x12\x14\n\x0c\x66ile_content\x18\x04 \x01(\t\"F\n\x0b\x46ileDetails\x12\x16\n\x0e\x63ontainer_name\x18\x01 \x01(\t\x12\x11\n\tfile_name\x18\x02 \x01(\t\x12\x0c\n\x04path\x18\x03 \x01(\t\"J\n\rFolderDetails\x12\x16\n\x0e\x63ontainer_name\x18\x01 \x01(\t\x12\x13\n\x0b\x66older_name\x18\x02 \x01(\t\x12\x0c\n\x04path\x18\x03 \x01(\t\"\x1f\n\x0c\x43opyResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"\x1d\n\rFilesResponse\x12\x0c\n\x04line\x18\x01 \x01(\t\"&\n\x12\x44irectoryStrcuture\x12\x10\n\x08yaml_rep\x18\x01 \x01(\t2\xbe\x01\n\x05\x46iles\x12\x39\n\x13\x63opyFileToContainer\x12\x0b.files.File\x1a\x13.files.CopyResponse\"\x00\x12\x37\n\x07getFile\x12\x12.files.FileDetails\x1a\x14.files.FilesResponse\"\x00\x30\x01\x12\x41\n\x0cgetDirectory\x12\x14.files.FolderDetails\x1a\x19.files.DirectoryStrcuture\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'files_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_FILE']._serialized_start=22
  _globals['_FILE']._serialized_end=107
  _globals['_FILEDETAILS']._serialized_start=109
  _globals['_FILEDETAILS']._serialized_end=179
  _globals['_FOLDERDETAILS']._serialized_start=181
  _globals['_FOLDERDETAILS']._serialized_end=255
  _globals['_COPYRESPONSE']._serialized_start=257
  _globals['_COPYRESPONSE']._serialized_end=288
  _globals['_FILESRESPONSE']._serialized_start=290
  _globals['_FILESRESPONSE']._serialized_end=319
  _globals['_DIRECTORYSTRCUTURE']._serialized_start=321
  _globals['_DIRECTORYSTRCUTURE']._serialized_end=359
  _globals['_FILES']._serialized_start=362
  _globals['_FILES']._serialized_end=552
# @@protoc_insertion_point(module_scope)
