# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
from definitions import files_pb2 as definitions_dot_files__pb2


class FilesStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.copyFilesToContainer = channel.stream_unary(
            "/files.Files/copyFilesToContainer",
            request_serializer=definitions_dot_files__pb2.FilesToCopy.SerializeToString,
            response_deserializer=definitions_dot_files__pb2.CopyResponse.FromString,
        )


class FilesServicer(object):
    """Missing associated documentation comment in .proto file."""

    def copyFilesToContainer(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_FilesServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "copyFilesToContainer": grpc.stream_unary_rpc_method_handler(
            servicer.copyFilesToContainer,
            request_deserializer=definitions_dot_files__pb2.FilesToCopy.FromString,
            response_serializer=definitions_dot_files__pb2.CopyResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "files.Files", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class Files(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def copyFilesToContainer(
        request_iterator,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            "/files.Files/copyFilesToContainer",
            definitions_dot_files__pb2.FilesToCopy.SerializeToString,
            definitions_dot_files__pb2.CopyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )
