# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from definitions import logs_pb2 as logs__pb2


class LogsStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.getDockerLogs = channel.unary_stream(
                '/logs.Logs/getDockerLogs',
                request_serializer=logs__pb2.Container.SerializeToString,
                response_deserializer=logs__pb2.ContainerLogs.FromString,
                )
        self.getComposeLogs = channel.unary_stream(
                '/logs.Logs/getComposeLogs',
                request_serializer=logs__pb2.Project.SerializeToString,
                response_deserializer=logs__pb2.ContainerLogs.FromString,
                )


class LogsServicer(object):
    """Missing associated documentation comment in .proto file."""

    def getDockerLogs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getComposeLogs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LogsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'getDockerLogs': grpc.unary_stream_rpc_method_handler(
                    servicer.getDockerLogs,
                    request_deserializer=logs__pb2.Container.FromString,
                    response_serializer=logs__pb2.ContainerLogs.SerializeToString,
            ),
            'getComposeLogs': grpc.unary_stream_rpc_method_handler(
                    servicer.getComposeLogs,
                    request_deserializer=logs__pb2.Project.FromString,
                    response_serializer=logs__pb2.ContainerLogs.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'logs.Logs', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Logs(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def getDockerLogs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/logs.Logs/getDockerLogs',
            logs__pb2.Container.SerializeToString,
            logs__pb2.ContainerLogs.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def getComposeLogs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/logs.Logs/getComposeLogs',
            logs__pb2.Project.SerializeToString,
            logs__pb2.ContainerLogs.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
