# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: logs.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nlogs.proto\x12\x04logs\"#\n\tContainer\x12\x16\n\x0e\x63ontainer_name\x18\x01 \x01(\t\"\x1f\n\x07Project\x12\x14\n\x0cproject_name\x18\x01 \x01(\t\" \n\rContainerLogs\x12\x0f\n\x07message\x18\x01 \x01(\t2{\n\x04Logs\x12\x39\n\rgetDockerLogs\x12\x0f.logs.Container\x1a\x13.logs.ContainerLogs\"\x00\x30\x01\x12\x38\n\x0egetComposeLogs\x12\r.logs.Project\x1a\x13.logs.ContainerLogs\"\x00\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'logs_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_CONTAINER']._serialized_start=20
  _globals['_CONTAINER']._serialized_end=55
  _globals['_PROJECT']._serialized_start=57
  _globals['_PROJECT']._serialized_end=88
  _globals['_CONTAINERLOGS']._serialized_start=90
  _globals['_CONTAINERLOGS']._serialized_end=122
  _globals['_LOGS']._serialized_start=124
  _globals['_LOGS']._serialized_end=247
# @@protoc_insertion_point(module_scope)
