# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: retrieve.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eretrieve.proto\x12\x0c\x64\x61ta_service\"<\n\x1aRetrieveInformationRequest\x12\x0c\n\x04user\x18\x01 \x01(\t\x12\x10\n\x08\x65nv_name\x18\x02 \x01(\t\"0\n\x1bRetrieveInformationResponse\x12\x11\n\tjson_data\x18\x01 \x01(\t2{\n\x0b\x44\x61taService\x12l\n\x13RetrieveInformation\x12(.data_service.RetrieveInformationRequest\x1a).data_service.RetrieveInformationResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'retrieve_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_RETRIEVEINFORMATIONREQUEST']._serialized_start=32
  _globals['_RETRIEVEINFORMATIONREQUEST']._serialized_end=92
  _globals['_RETRIEVEINFORMATIONRESPONSE']._serialized_start=94
  _globals['_RETRIEVEINFORMATIONRESPONSE']._serialized_end=142
  _globals['_DATASERVICE']._serialized_start=144
  _globals['_DATASERVICE']._serialized_end=267
# @@protoc_insertion_point(module_scope)
