"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.message
import sys

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class RetrieveInformationRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    USER_FIELD_NUMBER: builtins.int
    ENV_NAME_FIELD_NUMBER: builtins.int
    user: builtins.str
    env_name: builtins.str
    def __init__(
        self,
        *,
        user: builtins.str = ...,
        env_name: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["env_name", b"env_name", "user", b"user"]) -> None: ...

global___RetrieveInformationRequest = RetrieveInformationRequest

@typing_extensions.final
class RetrieveInformationResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    JSON_DATA_FIELD_NUMBER: builtins.int
    json_data: builtins.str
    def __init__(
        self,
        *,
        json_data: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["json_data", b"json_data"]) -> None: ...

global___RetrieveInformationResponse = RetrieveInformationResponse
