# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from definitions import uptime_pb2 as uptime__pb2


class ContainerUptimeStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.get_container_status = channel.unary_stream(
                '/uptime.ContainerUptime/get_container_status',
                request_serializer=uptime__pb2.Container.SerializeToString,
                response_deserializer=uptime__pb2.Response.FromString,
                )


class ContainerUptimeServicer(object):
    """Missing associated documentation comment in .proto file."""

    def get_container_status(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ContainerUptimeServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'get_container_status': grpc.unary_stream_rpc_method_handler(
                    servicer.get_container_status,
                    request_deserializer=uptime__pb2.Container.FromString,
                    response_serializer=uptime__pb2.Response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'uptime.ContainerUptime', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ContainerUptime(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def get_container_status(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/uptime.ContainerUptime/get_container_status',
            uptime__pb2.Container.SerializeToString,
            uptime__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
