# Generated by Django 4.1.7 on 2023-03-27 06:52

from django.db import migrations, models
import django.db.models.deletion
import user.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KuberUser',
            fields=[
                ('user_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('environments', models.JSONField(default=dict, validators=[user.models.validate_env_ids])),
                ('active_containers', models.JSONField(default=dict, validators=[user.models.validate_container_ids])),
                ('github_username', models.CharField(blank=True, editable=False, max_length=100, null=True)),
                ('github_repos', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('env_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('env_name', models.CharField(max_length=100, unique=True)),
                ('dockerimage', models.CharField(max_length=100)),
                ('config', models.JSONField(default=dict)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator_id', to='user.kuberuser')),
            ],
        ),
        migrations.CreateModel(
            name='Container',
            fields=[
                ('container_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('container_name', models.CharField(max_length=100)),
                ('config', models.JSONField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userid', to='user.kuberuser')),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='environment_id', to='user.environment')),
            ],
        ),
    ]
