# Generated by Django 4.2.2 on 2023-07-25 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kuberuser',
            name='email',
            field=models.EmailField(max_length=100, null=True, unique=True),
        ),
    ]
