# Generated by Django 4.2 on 2023-04-14 06:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kuberuser",
            name="github_repos",
            field=models.JSONField(default={}, null=True),
        ),
    ]
