# Generated by Django 4.2 on 2023-04-17 10:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0003_alter_kuberuser_github_repos"),
    ]

    operations = [
        migrations.RenameField(
            model_name="kuberuser",
            old_name="user_id",
            new_name="id",
        ),
    ]
