# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
from definitions import container_pb2 as definitions_dot_container__pb2


class ContainersStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.createContainer = channel.unary_stream(
            "/container.Containers/createContainer",
            request_serializer=definitions_dot_container__pb2.Container.SerializeToString,
            response_deserializer=definitions_dot_container__pb2.ContainerCreationResponse.FromString,
        )


class ContainersServicer(object):
    """Missing associated documentation comment in .proto file."""

    def createContainer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_ContainersServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "createContainer": grpc.unary_stream_rpc_method_handler(
            servicer.createContainer,
            request_deserializer=definitions_dot_container__pb2.Container.FromString,
            response_serializer=definitions_dot_container__pb2.ContainerCreationResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "container.Containers", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class Containers(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def createContainer(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_stream(
            request,
            target,
            "/container.Containers/createContainer",
            definitions_dot_container__pb2.Container.SerializeToString,
            definitions_dot_container__pb2.ContainerCreationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )
