# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: environment.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x65nvironment.proto\x12\x0b\x65nvironment\"\x82\x01\n\x12\x45nvironmentRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0b\n\x03tag\x18\x02 \x01(\t\x12\x0e\n\x06\x63onfig\x18\x03 \x01(\t\x12\x0e\n\x06images\x18\x04 \x03(\t\x12\r\n\x05\x66iles\x18\x05 \x03(\t\x12\x0c\n\x04type\x18\x06 \x01(\t\x12\x14\n\x0cproject_name\x18\x07 \x01(\t\"\x17\n\tEnvModReq\x12\n\n\x02id\x18\x01 \x01(\t\"K\n\x13\x45nvCreationResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x12\n\ncontainers\x18\x02 \x03(\t\x12\x0f\n\x07success\x18\x03 \x01(\x08\"\x1b\n\x08Response\x12\x0f\n\x07message\x18\x01 \x01(\t2\xf1\x01\n\x0b\x65nvironment\x12X\n\x11\x63reateEnvironment\x12\x1f.environment.EnvironmentRequest\x1a .environment.EnvCreationResponse\"\x00\x12\x44\n\x11\x64\x65leteEnvironment\x12\x16.environment.EnvModReq\x1a\x15.environment.Response\"\x00\x12\x42\n\x0fstopEnvironment\x12\x16.environment.EnvModReq\x1a\x15.environment.Response\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'environment_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_ENVIRONMENTREQUEST']._serialized_start=35
  _globals['_ENVIRONMENTREQUEST']._serialized_end=165
  _globals['_ENVMODREQ']._serialized_start=167
  _globals['_ENVMODREQ']._serialized_end=190
  _globals['_ENVCREATIONRESPONSE']._serialized_start=192
  _globals['_ENVCREATIONRESPONSE']._serialized_end=267
  _globals['_RESPONSE']._serialized_start=269
  _globals['_RESPONSE']._serialized_end=296
  _globals['_ENVIRONMENT']._serialized_start=299
  _globals['_ENVIRONMENT']._serialized_end=540
# @@protoc_insertion_point(module_scope)
