# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: definitions/image.proto
"""Generated protocol buffer code."""
from google.protobuf import (
    descriptor as _descriptor, descriptor_pool as _descriptor_pool,
    symbol_database as _symbol_database,
)
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x17\x64\x65\x66initions/image.proto\x12\x05image"6\n\x05Image\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x12\n\ndockerfile\x18\x02 \x01(\x0c\x12\x0b\n\x03tag\x18\x03 \x01(\t"$\n\x05\x45rror\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\r\n\x05\x65rror\x18\x02 \x01(\t"$\n\x07Success\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\x0b\n\x03msg\x18\x02 \x01(\t"/\n\x11ImageBuildSuccess\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04logs\x18\x02 \x01(\t"m\n\x12ImageBuildResponse\x12+\n\x07success\x18\x01 \x01(\x0b\x32\x18.image.ImageBuildSuccessH\x00\x12\x1d\n\x05\x65rror\x18\x02 \x01(\x0b\x32\x0c.image.ErrorH\x00\x42\x0b\n\tresponses"R\n\x14ImageRegistryDetails\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0b\n\x03tag\x18\x02 \x01(\t\x12\x0b\n\x03hub\x18\x03 \x01(\t\x12\x12\n\ncredential\x18\x04 \x01(\t"`\n\x0fGenericResponse\x12!\n\x07success\x18\x01 \x01(\x0b\x32\x0e.image.SuccessH\x00\x12\x1d\n\x05\x65rror\x18\x02 \x01(\x0b\x32\x0c.image.ErrorH\x00\x42\x0b\n\tresponses2\x87\x01\n\x06Images\x12\x39\n\nbuildImage\x12\x0c.image.Image\x1a\x19.image.ImageBuildResponse"\x00\x30\x01\x12\x42\n\tpushImage\x12\x1b.image.ImageRegistryDetails\x1a\x16.image.GenericResponse"\x00\x62\x06proto3'
)

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "definitions.image_pb2", globals())
if _descriptor._USE_C_DESCRIPTORS == False:
    DESCRIPTOR._options = None
    _IMAGE._serialized_start = 34
    _IMAGE._serialized_end = 88
    _ERROR._serialized_start = 90
    _ERROR._serialized_end = 126
    _SUCCESS._serialized_start = 128
    _SUCCESS._serialized_end = 164
    _IMAGEBUILDSUCCESS._serialized_start = 166
    _IMAGEBUILDSUCCESS._serialized_end = 213
    _IMAGEBUILDRESPONSE._serialized_start = 215
    _IMAGEBUILDRESPONSE._serialized_end = 324
    _IMAGEREGISTRYDETAILS._serialized_start = 326
    _IMAGEREGISTRYDETAILS._serialized_end = 408
    _GENERICRESPONSE._serialized_start = 410
    _GENERICRESPONSE._serialized_end = 506
    _IMAGES._serialized_start = 509
    _IMAGES._serialized_end = 644
# @@protoc_insertion_point(module_scope)
