# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
from definitions import image_pb2 as definitions_dot_image__pb2


class ImagesStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.buildImage = channel.unary_stream(
            "/image.Images/buildImage",
            request_serializer=definitions_dot_image__pb2.Image.SerializeToString,
            response_deserializer=definitions_dot_image__pb2.ImageBuildResponse.FromString,
        )
        self.pushImage = channel.unary_unary(
            "/image.Images/pushImage",
            request_serializer=definitions_dot_image__pb2.ImageRegistryDetails.SerializeToString,
            response_deserializer=definitions_dot_image__pb2.GenericResponse.FromString,
        )


class ImagesServicer(object):
    """Missing associated documentation comment in .proto file."""

    def buildImage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def pushImage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_ImagesServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "buildImage": grpc.unary_stream_rpc_method_handler(
            servicer.buildImage,
            request_deserializer=definitions_dot_image__pb2.Image.FromString,
            response_serializer=definitions_dot_image__pb2.ImageBuildResponse.SerializeToString,
        ),
        "pushImage": grpc.unary_unary_rpc_method_handler(
            servicer.pushImage,
            request_deserializer=definitions_dot_image__pb2.ImageRegistryDetails.FromString,
            response_serializer=definitions_dot_image__pb2.GenericResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "image.Images", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class Images(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def buildImage(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_stream(
            request,
            target,
            "/image.Images/buildImage",
            definitions_dot_image__pb2.Image.SerializeToString,
            definitions_dot_image__pb2.ImageBuildResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def pushImage(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/image.Images/pushImage",
            definitions_dot_image__pb2.ImageRegistryDetails.SerializeToString,
            definitions_dot_image__pb2.GenericResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )
