# Generated by Django 4.2 on 2023-06-07 11:25

import uuid

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DockerEnvironment",
            fields=[
                (
                    "env_id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("env_name", models.CharField(max_length=100, unique=True)),
                (
                    "images",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=100), size=None
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("config", models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name="UserDockerEnvironments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
    ]
