# Generated by Django 4.2.2 on 2023-09-04 02:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DockerImage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('Dockerfile', models.CharField(max_length=1000)),
                ('private', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('env_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('env_name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('config', models.JSONField(default=dict)),
                ('type', models.CharField(choices=[('compose', 'docker-compose'), ('docker', 'docker')], max_length=10)),
                ('private', models.BooleanField(default=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='environment.dockerimage')),
            ],
        ),
        migrations.CreateModel(
            name='Sandbox',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('private', models.BooleanField(default=False)),
                ('containers', models.JSONField(blank=True, default=dict, null=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('env', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='environment.environment')),
            ],
        ),
        migrations.AddConstraint(
            model_name='sandbox',
            constraint=models.UniqueConstraint(fields=('creator', 'env'), name='user_env_pk'),
        ),
    ]
