# Generated by Django 4.2.2 on 2023-09-04 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('environment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='sandbox',
            name='user_env_pk',
        ),
        migrations.AlterField(
            model_name='sandbox',
            name='private',
            field=models.BooleanField(default=True),
        ),
    ]
