# Generated by Django 4.2.2 on 2023-08-27 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('environment', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sandbox',
            name='env',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='environment.environment'),
        ),
    ]
