# Generated by Django 4.2.2 on 2023-07-19 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('environment', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnvironmentTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github_url', models.URLField(max_length=100)),
                ('test_command', models.CharField(max_length=100)),
                ('directory', models.CharField(blank=True, max_length=200)),
                ('setup_command', models.CharField(blank=True, max_length=100)),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='environment.environment')),
            ],
        ),
    ]
