/**
 * @fileoverview gRPC-Web generated client stub for container
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.4.2
// 	protoc              v3.12.4
// source: container.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');

const proto = {};
proto.container = require('./container_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.container.ContainersClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.container.ContainersPromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.container.Container,
 *   !proto.container.ContainerCreationResponse>}
 */
const methodDescriptor_Containers_createContainer = new grpc.web.MethodDescriptor(
  '/container.Containers/createContainer',
  grpc.web.MethodType.SERVER_STREAMING,
  proto.container.Container,
  proto.container.ContainerCreationResponse,
  /**
   * @param {!proto.container.Container} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.container.ContainerCreationResponse.deserializeBinary
);


/**
 * @param {!proto.container.Container} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.container.ContainerCreationResponse>}
 *     The XHR Node Readable Stream
 */
proto.container.ContainersClient.prototype.createContainer =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/container.Containers/createContainer',
      request,
      metadata || {},
      methodDescriptor_Containers_createContainer);
};


/**
 * @param {!proto.container.Container} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.container.ContainerCreationResponse>}
 *     The XHR Node Readable Stream
 */
proto.container.ContainersPromiseClient.prototype.createContainer =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/container.Containers/createContainer',
      request,
      metadata || {},
      methodDescriptor_Containers_createContainer);
};


module.exports = proto.container;
